version: '3'

services:
  es:
    build: ./  # Elasticsearch用のDockerfileがあるディレクトリを指定
    container_name: elasticsearch-python
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=es-python-cluster
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false
      - http.port=9200
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-python:9200

  python_app:
    build: ./python  # Python 3.11用のDockerfileがあるディレクトリを指定
    # 必要に応じてPythonコンテナ内のアプリケーションを指定
    ports:
      - "8000:8000"  # 例えば、FastAPIアプリケーションを起動する場合
    # command: python app.py  # Pythonのデフォルト起動コマンドを指定する場合

volumes:
  es-data: null
